/**
 * 약관 시드 SQL 생성기.
 *
 *   node scripts/seed-legal.mjs
 *
 * 코드 안의 정책 문안(`lib/content/*`)을 HTML 로 바꿔
 * `supabase/migrations/20260908002200_legal_documents.sql` 의 SEED 구간에 써 넣는다.
 * 문안을 손으로 HTML 에 옮겨 적지 않는 이유는 하나다 — 두 벌이 되는 순간 어느 쪽이
 * 진짜인지 알 수 없게 되고, 오탈자 하나가 법률 문서에 영구히 남는다.
 *
 * DDL 은 손으로 쓴 그대로 두고 마커 사이만 갈아 끼운다. 스키마 변경 이력은 사람이
 * 읽어야 하고, 생성기 문자열 안에 숨겨 두면 리뷰가 불가능해진다.
 *
 * TypeScript 소스를 직접 읽는다. Node 의 타입 스트리핑은 켜져 있지만 확장자 없는
 * 상대 경로와 `@/` 별칭은 해석하지 못하므로, 그 두 가지만 훅으로 채워 준다.
 */
import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { registerHooks } from 'node:module'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const MIGRATION_PATH = path.join(
  ROOT,
  'supabase/migrations/20260908002200_legal_documents.sql',
)

const BEGIN_MARKER = '-- >>> SEED (generated by scripts/seed-legal.mjs — do not edit by hand) >>>'
const END_MARKER = '-- <<< SEED <<<'

registerHooks({
  resolve(specifier, context, nextResolve) {
    if (specifier.startsWith('@/')) {
      return nextResolve(pathToFileURL(path.join(ROOT, `${specifier.slice(2)}.ts`)).href, context)
    }

    if (specifier.startsWith('.') && path.extname(specifier) === '') {
      const parentPath = fileURLToPath(context.parentURL)
      const candidate = path.resolve(path.dirname(parentPath), `${specifier}.ts`)

      if (existsSync(candidate)) {
        return nextResolve(pathToFileURL(candidate).href, context)
      }
    }

    return nextResolve(specifier, context)
  },
})

const { policySectionsToHtml, escapeHtml } = await import('../lib/content/policy-to-html.ts')
const { sanitizeLegalHtml } = await import('../lib/sanitize/legal-html.ts')
const operating = await import('../lib/content/operating-policy.ts')
const privacy = await import('../lib/content/privacy-policy.ts')

/** `2026년 9월 18일` → `2026-09-18`. 시행일의 단일 출처는 코드의 그 문자열이다. */
function toIsoDate(korean) {
  const match = /^(\d{4})년\s*(\d{1,2})월\s*(\d{1,2})일$/u.exec(korean.trim())

  if (match === null) {
    throw new Error(`시행일 형식을 읽지 못했습니다: ${korean}`)
  }

  return `${match[1]}-${match[2].padStart(2, '0')}-${match[3].padStart(2, '0')}`
}

/* 디스코드 운영정책은 확정 문안이 아직 없다. 사용자 사이트가 지금 보여 주는
   안내 문단을 그대로 최초 발행본으로 심어, 관리자에서 곧바로 갈아 끼울 수 있게 한다. */
const DISCORD_PARAGRAPHS = [
  '글자월드 공식 디스코드 서버는 모두가 안전하게 즐길 수 있는 공간을 목표로 운영됩니다.',
  '정식 운영정책 문안은 준비 중입니다. 확정되는 대로 이 페이지에 게시합니다.',
]

const documents = [
  {
    slug: 'privacy',
    title: privacy.PRIVACY_POLICY_TITLE,
    version: privacy.PRIVACY_POLICY_VERSION,
    effectiveDate: toIsoDate(privacy.PRIVACY_POLICY_EFFECTIVE_DATE),
    summary: '코드 문안(lib/content/privacy-policy)을 옮긴 최초 발행본.',
    html: policySectionsToHtml({ sections: privacy.PRIVACY_POLICY_SECTIONS }),
  },
  {
    slug: 'discord',
    title: '디스코드 운영정책',
    version: privacy.PRIVACY_POLICY_VERSION,
    effectiveDate: toIsoDate(privacy.PRIVACY_POLICY_EFFECTIVE_DATE),
    summary: '확정 문안 이전의 안내 문단.',
    html: DISCORD_PARAGRAPHS.map((text) => `<p>${escapeHtml(text)}</p>`).join(''),
  },
  {
    slug: 'operating',
    title: operating.OPERATING_POLICY_TITLE,
    version: operating.OPERATING_POLICY_VERSION,
    effectiveDate: toIsoDate(operating.OPERATING_POLICY_EFFECTIVE_DATE),
    summary: '코드 문안(lib/content/operating-policy)을 옮긴 최초 발행본.',
    html: policySectionsToHtml({
      sections: operating.OPERATING_POLICY_SECTIONS,
      addendum: operating.OPERATING_POLICY_ADDENDUM,
    }),
  },
]

/** 작은따옴표만 이스케이프하면 되는 짧은 값. 본문은 달러 인용부호를 쓴다. */
function sqlText(value) {
  return `'${value.replace(/'/gu, "''")}'`
}

function seedFor(document) {
  /* 정제기를 한 번 통과시킨 값만 심는다. 관리자가 저장할 때와 같은 규칙을 거쳐야
     "시드본은 되는데 저장하면 태그가 사라지는" 차이가 생기지 않는다. */
  const html = sanitizeLegalHtml(document.html)

  if (html.includes('$legal$')) {
    throw new Error(`본문에 달러 인용부호가 들어 있습니다: ${document.slug}`)
  }

  return `insert into public.legal_documents (slug, title)
values (${sqlText(document.slug)}, ${sqlText(document.title)})
on conflict (slug) do nothing;

insert into public.legal_document_versions (
  document_id, version, effective_date, content_html, summary, is_published, published_at
)
select
  d.id,
  ${sqlText(document.version)},
  date ${sqlText(document.effectiveDate)},
  $legal$${html}$legal$,
  ${sqlText(document.summary)},
  true,
  now()
from public.legal_documents d
where d.slug = ${sqlText(document.slug)}
on conflict (document_id, version) do nothing;`
}

const HEADER = [
  '-- 최초 발행본. `on conflict do nothing` 이라 재실행해도 운영자가 이미 고친',
  '-- 문안을 덮어쓰지 않는다.',
].join('\n')

const seed = [HEADER, ...documents.map(seedFor)].join('\n\n')

const source = await readFile(MIGRATION_PATH, 'utf8')
const begin = source.indexOf(BEGIN_MARKER)
const end = source.indexOf(END_MARKER)

if (begin < 0 || end < begin) {
  throw new Error('마이그레이션에서 SEED 마커를 찾지 못했습니다.')
}

const next = `${source.slice(0, begin + BEGIN_MARKER.length)}\n${seed}\n${source.slice(end)}`

await writeFile(MIGRATION_PATH, next, 'utf8')

for (const document of documents) {
  console.log(`[seed-legal] ${document.slug} ${document.version} ${document.html.length}자`)
}
